title: BLOGGGGGGG
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: "hayeonggyeong.github.io/blog_pf/"
baseurl:"/blog_pf"
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: blog_pf/index.html
  - title: About
    url: blog_pf/about
  - title: Contact
    url: blog_pf/contact

social:
  github: brianmaierjr
  twitter: brianmaierjr
  facebook: brianmaierjr
  email: brimaidesigns@gmail.com
  linkedin: brianmaierjr

google_analytics: "UA-58263416-1"

disqus:
    shortname: brianmaierjr

remote_theme : brianmaierjr/long-haul
